const express = require('express');
const multer = require('multer');
const AdmZip = require('adm-zip');
const path = require('path');
const crypto = require('crypto');
const app = express();
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');next()});
const upload = multer({storage: multer.memoryStorage(), limits:{fileSize:100*1024*1024}});
const runs = new Map();
const SOURCE_EXT = /\.(js|jsx|ts|tsx|cjs|mjs|py|java|go|rb|php|cs|json|yml|yaml)$/i;
function lineAt(text,index){return text.slice(0,index).split('\n').length}
function snippet(text,line){const rows=text.split('\n'),from=Math.max(0,line-3),to=Math.min(rows.length,line+3);return rows.slice(from,to).map((x,i)=>`${String(from+i+1).padStart(4)} | ${x}`).join('\n')}
function controls(context,type){const c=[];if(/https:|requireHttps|httpsOnly/i.test(context))c.push('HTTPS enforcement');if(/allowlist|allowedHosts|allowed.*host/i.test(context))c.push('Hostname allowlist validation');if(/private|loopback|reserved|127\.0\.0\.1|169\.254/i.test(context))c.push('Private/local/reserved address blocking');if(/dns\.|resolve\(|lookup\(/i.test(context))c.push('DNS resolution validation');if(/pin(ned|ning)|localAddress|agent/i.test(context))c.push('Connection pinning');if(/auth|session|token|bearer|requireUser/i.test(context)&&type==='idor')c.push('Authentication/session validation');if(/authorize|ownership|ownerId|permission|role|canAccess/i.test(context)&&type==='idor')c.push('Resource authorization check');return c}
function finding(file,text,index,ruleId,title,category,severity,reason,type,recommendation){const line=lineAt(text,index),context=text.split('\n').slice(Math.max(0,line-8),line+8).join('\n'),securityControls=controls(context,type);let confidence=type==='secret'?86:type==='idor'?64:70;if(securityControls.length)confidence=Math.max(12,confidence-securityControls.length*18);return {id:'',ruleId,title,category,severity:securityControls.length>=2?'informational':severity,confidence,status:securityControls.length>=2?'NOT CONFIRMED':'NEEDS REVIEW',file,line,column:1,evidence:snippet(text,line),description:reason,reason,securityControls,recommendation,affectedAsset:path.basename(file),createdAt:new Date().toISOString()}}
function analyze(files){const findings=[];for(const f of files){const text=f.content,add=(idx,...args)=>findings.push(finding(f.path,text,idx,...args));let m;const outbound=/(?:fetch\s*\(|axios\.(?:get|post|request)\s*\(|https?\.request\s*\()/g;while((m=outbound.exec(text))){const nearby=text.slice(Math.max(0,m.index-700),m.index+900);if(/url|uri|endpoint|webhook|req\.|body\.|params\.|query\./i.test(nearby))add(m.index,'SSRF-001','Potential SSRF in outbound request','SSRF','medium','User-influenced URL or endpoint appears to reach an outbound request API.','ssrf','Validate destination URLs, block private/reserved addresses, and pin validated connections.')}const resource=/(?:req\.(?:params|query|body)\.(?:userId|accountId|profileId|documentId|resourceId)|params\.(?:userId|accountId|profileId|documentId|resourceId))/g;while((m=resource.exec(text)))add(m.index,'IDOR-001','Potential resource authorization gap','Broken Access Control / IDOR','medium','A request-derived resource identifier is used in a sensitive code path; authorization evidence was evaluated nearby.','idor','Derive identity from a validated session and enforce ownership or role authorization before access.');const secret=/(?:api[_-]?key|secret|password|token)\s*[:=]\s*['\"][A-Za-z0-9_\-]{12,}['\"]/gi;while((m=secret.exec(text))){if(!/example|placeholder|changeme|your[_-]/i.test(m[0]))add(m.index,'SECRET-001','Potential hardcoded secret','Sensitive Information','high','A credential-like literal was found in source code.','secret','Move secrets to a managed secret store or environment variable and rotate exposed values.')}const cors=/Access-Control-Allow-Origin\s*[:=]\s*['\"]\*|origin\s*:\s*['\"]\*/g;while((m=cors.exec(text)))add(m.index,'CONFIG-001','Permissive CORS configuration','Security Configuration','medium','Wildcard CORS configuration may expose browser-facing endpoints.','config','Restrict allowed origins to trusted application origins.')}findings.forEach((f,i)=>f.id=`F-${String(i+1).padStart(3,'0')}`);return findings}
function unpack(buffer){const zip=new AdmZip(buffer),files=[];for(const entry of zip.getEntries()){if(entry.isDirectory||!SOURCE_EXT.test(entry.entryName)||entry.header.size>1024*1024)continue;files.push({path:entry.entryName,content:entry.getData().toString('utf8')})}return files}
app.get('/',(req,res)=>res.type('html').send('<main style="font-family:system-ui;padding:3rem;color:#172235"><h1>Sentinel Assessment API</h1><p>The source-analysis service is running.</p><p>Use <code>POST /api/assess</code> with a ZIP archive, or check <a href="/api/health">/api/health</a>.</p></main>'));
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.post('/api/assess',upload.single('source'),(req,res)=>{try{if(!req.file||!req.file.originalname.toLowerCase().endsWith('.zip'))return res.status(400).json({error:'Upload a ZIP archive.'});const files=unpack(req.file.buffer);if(!files.length)return res.status(400).json({error:'No supported source files found in ZIP.'});const findings=analyze(files),id=`ASM-${crypto.randomUUID().slice(0,8).toUpperCase()}`,run={assessmentId:id,application:req.body.application||path.basename(req.file.originalname,'.zip'),startTime:new Date().toISOString(),endTime:new Date().toISOString(),status:'COMPLETED',filesAnalyzed:files.length,rulesExecuted:['SSRF-001','IDOR-001','SECRET-001','CONFIG-001'],findings,inventory:files.map(f=>f.path),scope:'Uploaded source-code archive · static analysis only'};runs.set(id,run);res.json(run)}catch(e){res.status(400).json({error:`Unable to inspect archive: ${e.message}`})}});
app.get('/api/runs/:id',(req,res)=>runs.has(req.params.id)?res.json(runs.get(req.params.id)):res.status(404).json({error:'Assessment not found'}));
app.use((err,req,res,next)=>res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'ZIP archive exceeds the 100 MB analysis limit.':`Assessment upload failed: ${err.message}`}));
app.listen(5174,()=>console.log('Assessment API listening on http://127.0.0.1:5174'));
