import React, { useEffect, useState } from 'react';
import './isolation.css';
import { DEMO_INCIDENT } from './demoData.js';

const phases = ['Awaiting approval', 'Provisioning vCluster', 'Isolating namespace', 'Replaying payload', 'Exploit reproduced', 'Evidence captured · environment destroyed'];
const output = [`$ sentry isolate --alert ${DEMO_INCIDENT.id}`, '✓ vcluster provisioned · 1.8s', '✓ Namespace isolated · network egress restricted', `✓ Synthetic ${DEMO_INCIDENT.vector} probe replayed against anonymized service twin`, '⚠ Container terminated · simulated behavior reproduced', '✓ Evidence bundle sealed · 4 artifacts captured', '✓ Destroying vcluster · ephemeral resources released'];

export default function IsolationLab({ onBack }) {
  const [step, setStep] = useState(-1);
  const [evidenceOpen, setEvidenceOpen] = useState(false);
  const [selectedEvidence, setSelectedEvidence] = useState(0);
  useEffect(() => {
    if (step < 0 || step >= 5) return;
    const timer = setTimeout(() => setStep(s => Math.min(5, s + 1)), 1800);
    return () => clearTimeout(timer);
  }, [step]);
  const evidence = DEMO_INCIDENT.evidence;
  return <main className="isolation-page"><div className="iso-heading"><div><span className="eyebrow">CONTAINMENT LAB · PROTOTYPE</span><h1>Exploit isolation</h1><p>Reproduce threat behavior in an ephemeral digital twin. Production telemetry remains live throughout.</p></div><div className="iso-heading-actions"><button className="iso-evidence-button" onClick={()=>{setSelectedEvidence(0);setEvidenceOpen(true)}} disabled={step<5}>▤ &nbsp; View captured evidence</button><button className="iso-launch" onClick={()=>setStep(0)}>▶ &nbsp; Run isolation demo</button><button className="ghost" onClick={onBack}>← Live telemetry</button></div></div>
    <div className="iso-alert"><span className="iso-alert-icon">!</span><div><small>{DEMO_INCIDENT.severity} ALERT · {DEMO_INCIDENT.id} · SYNTHETIC DEMO</small><b>{DEMO_INCIDENT.isolationTitle} · {DEMO_INCIDENT.method} {DEMO_INCIDENT.endpoint}</b><span>Source {DEMO_INCIDENT.sourceIp} <i>·</i> {DEMO_INCIDENT.status} <i>·</i> Production protected</span></div><span className="iso-contained">● CONTAINED</span></div>
    <div className="iso-grid"><section className="iso-prod"><header><div><span className="iso-dot live"/><b>SYNTHETIC DEMO TARGET</b><small>SENTRY DEMO · {DEMO_INCIDENT.metrics.regionLabel}</small></div><span className="iso-live">● LIVE · HEALTHY</span></header><div className="prod-content"><div className="prod-kpis"><div><small>REQUESTS / MIN</small><b>{DEMO_INCIDENT.metrics.requestsPerMinute.toLocaleString()}</b><i>↗ 4.2%</i></div><div><small>API LATENCY</small><b>{DEMO_INCIDENT.metrics.averageLatencyMs}<span>ms</span></b><i>p95 · {DEMO_INCIDENT.metrics.p95LatencyMs}ms</i></div><div><small>SERVICE HEALTH</small><b className="healthy">{DEMO_INCIDENT.metrics.serviceHealthPercent}<span>%</span></b><i>All systems operational</i></div></div><div className="prod-chart"><div><b>Request volume</b><small>LAST 60 SECONDS</small></div><svg viewBox="0 0 600 120" preserveAspectRatio="none"><defs><linearGradient id="isoFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#67d9af" stopOpacity=".25"/><stop offset="1" stopColor="#67d9af" stopOpacity="0"/></linearGradient></defs><path d="M0 83 C30 80 35 44 70 55 S115 87 150 61 S190 73 225 44 S270 61 300 48 S340 73 375 39 S420 58 450 34 S490 58 520 30 S565 42 600 18 V120 H0Z" fill="url(#isoFill)"/><path d="M0 83 C30 80 35 44 70 55 S115 87 150 61 S190 73 225 44 S270 61 300 48 S340 73 375 39 S420 58 450 34 S490 58 520 30 S565 42 600 18" fill="none" stroke="#67d9af" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><div className="chart-axis"><span>60s ago</span><span>45s</span><span>30s</span><span>15s</span><span>now</span></div></div><div className="prod-foot"><span>◈ Edge protection active</span><span>↗ No payload forwarded to application</span></div></div></section>
    <section className={`iso-sandbox ${step>=4?'crashed':''}`}><header><div><span className="iso-dot sandbox-dot"/><b>EPHEMERAL SANDBOX</b><small>vCLUSTER · ANONYMIZED TWIN</small></div><span className={`sandbox-status ${step===5?'destroyed':step>=4?'reproduced':step>=0?'running':''}`}>{step===5?'DESTROYED':step>=4?'EXPLOIT REPRODUCED':step>=0?'RUNNING':'STANDBY'}</span></header><div className="sandbox-body"><div className="terminal-top"><span>TERMINAL / ISOLATED-NS-7F2A</span><span>● ● ●</span></div><div className="terminal-lines">{(step<0?output.slice(0,1):output.slice(0,Math.min(step+2,output.length))).map((line,i)=><div key={line} className={`term-line ${line.includes('⚠')?'term-warn':''}`}><span>{String(i+1).padStart(2,'0')}</span>{line}</div>)}{step>=0&&step<5&&<div className="term-cursor">▍</div>}</div>{step>=4&&<div className="crash-overlay"><div className="crash-mark">×</div><b>CONTAINER EXITED</b><span>Exit code 137 · behavior captured</span></div>}</div><footer><span>⛨ Network isolated</span><span>◌ Secrets redacted</span><span>◷ TTL 90 sec</span></footer></section></div>
    <div className="iso-controls"><div className="phase-progress">{phases.map((p,i)=><div key={p} className={step===i?'current':step>i?'done':''}><i>{step>i?'✓':String(i+1).padStart(2,'0')}</i><span>{p}</span></div>)}</div><div className="iso-action">{step<0?<><div><b>Safe replay · no production impact</b><span>Payload runs against a sanitized twin. Evidence is sealed before the cluster is destroyed.</span></div><span className="iso-demo-hint">Start the demo from the page header</span></>:step<5?<><div><b>{phases[step+1]}</b><span>Automated run in progress · production remains healthy</span></div><button className="iso-launch" disabled>◌ &nbsp; Running isolation…</button></>:<><div><b>Evidence secured · sandbox destroyed</b><span>Reproduction confirmed in isolated twin. No production requests were exposed.</span></div><span className="iso-demo-hint">Use the page header to replay</span></>}</div></div>
    <div className="iso-note"><span>ⓘ</span><p><b>Prototype simulation.</b> The terminal and sandbox lifecycle are demonstrative UI states; this page does not connect to a live vCluster or execute a real payload.</p></div>
    {evidenceOpen&&<div className="evidence-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEvidenceOpen(false)}}><section className="evidence-modal" role="dialog" aria-modal="true" aria-labelledby="evidence-title"><header><div><span className="eyebrow">ISOLATION RUN · {DEMO_INCIDENT.id}</span><h2 id="evidence-title">Captured evidence</h2><p>Demo evidence bundle sealed before the ephemeral sandbox was destroyed.</p></div><button className="evidence-close" onClick={()=>setEvidenceOpen(false)} aria-label="Close evidence">×</button></header><div className="evidence-modal-content"><nav className="evidence-files" aria-label="Evidence artifacts">{evidence.map((item,index)=><button key={item.name} className={selectedEvidence===index?'selected':''} onClick={()=>setSelectedEvidence(index)}><span className="evidence-file-icon">{index===0?'◫':'▤'}</span><span><b>{item.name}</b><small>{item.kind} · {item.size}</small></span><i>›</i></button>)}</nav><article className="evidence-detail"><div className="evidence-detail-icon">▤</div><span className="evidence-kind">{evidence[selectedEvidence].kind.toUpperCase()}</span><h3>{evidence[selectedEvidence].name}</h3><p>{evidence[selectedEvidence].detail}</p><div className="evidence-meta"><span>ALERT<b>{DEMO_INCIDENT.id} · {DEMO_INCIDENT.vector}</b></span><span>CAPTURED<b>Sandbox replay · just now</b></span><span>INTEGRITY HASH<b>{evidence[selectedEvidence].hash}</b></span><span>DATA HANDLING<b>Anonymized · secrets redacted</b></span></div><div className="evidence-sealed">✓ &nbsp; SYNTHETIC DEMO EVIDENCE · ISOLATED CAPTURE</div></article></div><footer><span>4 artifacts · 97 KB total</span><button onClick={()=>setEvidenceOpen(false)}>Close evidence</button></footer></section></div>}
  </main>;
}
